[build-system]
requires = [
    "setuptools>=46.4.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[[tool.mypy.overrides]]
module = [
    "bs4",
    "youtube_dl",
    "tqdm",
    "pdfkit",
]
ignore_missing_imports = true
