name: Test Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Check formatting with black and isort
        run: |
          black --check syncmymoodle
          isort --check-only syncmymoodle
      - name: Lint with flake8
        run: flake8 syncmymoodle
      - name: Analyze with mypy
        run: mypy syncmymoodle
